### ISSUE TITLE
Functions containing blocks are not available in Swift.

### ISSUE THREAD

**Issue by King-Wizard** [andreamazz/UITextField-Shake#11]
These three methods available below are not displayed by the auto-completion when using Swift:

```objc
- (void)shake:(int)times withDelta:(CGFloat)delta completion:(void((^)()))handler;
- (void)shake:(int)times withDelta:(CGFloat)delta speed:(NSTimeInterval)interval completion:(void((^)()))handler;
- (void)shake:(int)times withDelta:(CGFloat)delta speed:(NSTimeInterval)interval shakeDirection:(ShakeDirection)shakeDirection completion:(void((^)()))handler;
```

Nonetheless the others which do not use blocks are usable and displayed by the auto-completion tool in the last version of Xcode. I tried to call them manually in a Swift project (the three methods above) but I was not successful.

So to by-pass this problem I had to call these functions from an Objective-C class which itself was called by a Swift class. 

So you should fix this problem by rewriting this API in Swift.

Thank you in advance.

Best regards.

**Comment by andreamazz** [comment]
> So you should fix this problem by rewriting this API in Swift.

Or I can just fix it.  
Commit 0acb502 does that. 

Cheers
