### ISSUE TITLE
Position Independent Executable

### ISSUE THREAD

**Issue by Juice805** [andreamazz/UITextField-Shake#19]
First, thank you for this great work, it's extremely handy.

I am having warnings when uploading my app to the store after adding this framework from Cocoa Pods. They say the app is no longer a PIE and after reading [here](http://stackoverflow.com/questions/16518204/what-is-the-correct-xcode-setting-for-position-independent-executables) it seems it can be caused by other libraries. 

This is the only pod on this project so I'm almost certain it is the cause. I have tried the suggestions from the link above and while the command line tool shows the app has the PIE flag I continue to receive app store warnings. So it may also be an App store issue. 

Has anyone else reported this? I will continue searching on my end

**Comment by Juice805** [comment]
From the App Store:

Non-PIE Binary - The executable 'Payload/Resistor.app/Frameworks/UITextField_Shake.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

Non-PIE Binary - The executable 'UITextField_Shake.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

**Comment by andreamazz** [comment]
Hi @Juice805 
It's the first time I'm hearing about this, I have apps on the store using this library too, so I'm guessing it's an AppStore issue (last night I spent most of my time on the phone closing down App store alerts, might be related?).
The build flags seem ok, "Generate position-dependend code" is set to no (so it should be Position independent). I'll keep you posted if I find out more info.

**Comment by andreamazz** [comment]
The sample project is [PIE](https://developer.apple.com/library/ios/qa/qa1788/_index.html):
```
~/Desktop otool -hv TextFieldShake.app/TextFieldShake
TextFieldShake.app/TextFieldShake:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00     EXECUTE    20       3448   NOUNDEFS DYLDLINK TWOLEVEL PIE
```

**Comment by Juice805** [comment]
As is mine, however Apple disagrees
```
otool -hv Resistor 
Resistor:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   ARM64        ALL  0x00     EXECUTE    37       3760   NOUNDEFS DYLDLINK TWOLEVEL PIE
```

**Comment by andreamazz** [comment]
Checkout this issue:
https://github.com/CocoaPods/CocoaPods/issues/5453

Apparently it's an issue on Apple's side.

**Comment by Juice805** [comment]
Good news then 👍 Thanks again for the awesome framework!

**Comment by KamalHunzai** [comment]
I think this issue should be closed now. I was uploading my build last Friday ; got same warning messages for every framework i add via cocoa-pods.  
I saw this issue reported on 
https://github.com/CocoaPods/CocoaPods/issues/5453

They have closed the issue there. 
I got the warning email and a pop up on ipa upload but it's available for testing on iTunes connect.

**Comment by andreamazz** [comment]
Agree.
